FROM node:18-alpine as client-builder

WORKDIR /client
COPY view/package*.json ./
RUN npm install
COPY view/ .
RUN npm run build

FROM node:18-alpine as server-builder

WORKDIR /server
COPY server/package*.json ./
RUN npm install
COPY server/ .

FROM python:3.9 as python-seeder

WORKDIR /seeder
RUN apt-get update && apt-get install -y python3-pip libmysqlclient-dev
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
RUN pip3 install mysql-connector-python

FROM mysql:8

COPY ./dump/plutocinema.sql /docker-entrypoint-initdb.d/01.sql

COPY --from=client-builder /client/dist /app/client

COPY --from=server-builder /server /app/server

COPY --from=python-seeder /seeder /app/seeder

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=plutocinema
ENV MYSQL_ROOT_HOST=%

EXPOSE 3306 5000 4173

RUN apt-get update && apt-get install -y \
    libmysqlclient-dev && \
    pip3 install mysql-connector-python

CMD ["sh", "-c", "python3 /app/seeder/database/seeder.py > /dev/null 2>&1 && \
    node /app/server/index.js & \
    npm run preview --prefix /app/client -- --host"]
