FROM node:18-alpine as client-builder

WORKDIR /app
COPY view/package*.json ./
RUN npm install
COPY view/ .
RUN npm run build

FROM node:18-alpine as server-builder

WORKDIR /app
COPY server/package*.json ./
RUN npm install
COPY server/ .

FROM python:3.9-slim as python-seeder

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install mysql-connector-python

FROM mysql:8

COPY ./dump/plutocinema.sql /docker-entrypoint-initdb.d/01.sql
COPY --from=client-builder /app /app/client
COPY --from=server-builder /app /app/server
COPY --from=python-seeder /app /app/seeder

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=plutocinema
ENV MYSQL_ROOT_HOST=%

ENV DB_HOST=db
ENV DB_USER=root
ENV DB_PASS=root
ENV DB_NAME=plutocinema
ENV SERVER_PORT=5000
ENV SERVER_URL=http://localhost:5000
ENV CLIENT_URL=http://localhost:4173

EXPOSE 3306 5000 4173

CMD ["sh", "-c", "python /app/seeder/database/seeder.py > /dev/null 2>&1 && \
    node /app/server/index.js & \
    npm run preview --prefix /app/client -- --host"]
